inc:
  # Blog Information
  title:        "Bitcoin Bulls"
  subtitle:     "Helping investors earn bitcoin."
  cover_image:  /images/branding/bitcoin-bulls-375x358.png
  logo:         /branding/bitcoin-bulls-52x50.png
  
  # Company information
  company:      Bitcoin Bulls
  url:          http://www.bitcoinbulls.net/
  facebook:     BTCBulls
  twitter:      DavidSilvaSmith
  gplus:        '109243945202894778112'
  about_link:   /my-story/
  
  # Product Information
  product_link: /bitcoin-expert/
  tagline:      "I help CEOs too"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         false
    
  
 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

name: Bitcoin Bulls
markdown: kramdown
timezone: America/Detroit
highlighter: pygments
author: David Smith
safe: true
lsi: false
permalink: none

url: http://www.bitcoinbulls.net
exclude:  [CNAME, Gemfile, Gemfile.lock, '*.less', gruntfile.js, custom_css, node_modules, README.md, '*.svg', '*.docx']
include: [glyphicons-halflings-regular.svg]

sass:
    sass_dir: css
    style: :compressed

relative_permalinks: false
paginate: 10
paginate_path: "blog/page:num/"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: "post"
      is_post: true

