markdown: kramdown
timezone: America/Detroit
highlighter: rouge
safe: true
lsi: false
permalink: none

exclude:  [CNAME, Gemfile, Gemfile.lock, '*.less', gruntfile.js, custom_css, node_modules, README.md, '*.svg', '*.docx']
include: [glyphicons-halflings-regular.svg, ".well-known"]

gems:
  - jekyll-redirect-from
  - jekyll-paginate

lsi: false

sass:
    sass_dir: css
    style: :compressed

relative_permalinks: false
paginate: 10
paginate_path: "blog/page:num/"

whitelist: 
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      image: /images/branding/bitcoin-bull-sunset-1440x320-minified.png
      includeHeader: standard-image.html
      popularPostTitle: How to Earn Bitcoin Through Arbitrage Software (AKA a bot)
      changeFreq: WEEKLY
      excerpt: Bitcoin Bulls is a community for bitcoin investors seeking yield on their holdings.
      includes: links.md
      author: dave
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: "bitcoin-expert" # empty string for all files
    values:
      image: "/images/config/expert-cover.jpg"